### ISSUE TITLE
Шрифт не по макету

### ISSUE THREAD

**Issue by igosheva** [EgorKorol/burgers#4]
about__item__text - шрифт не по макету, видимо не подцепился

**Comment by igosheva** [comment]
about__item__title - начертание не по макету, слишком жирное.

**Comment by EgorKorol** [comment]
Проверил, все как надо стоит. Не знаю в чем проблема может быть.

**Comment by igosheva** [comment]
Так как шрифт у тебя один браузер должен понимать какое начртание применять к элементу. Нужно дополнительно для элементов с разной жирностью прописывать свойство font-weight. В данном случае нужно значение font-weight: 500;

**Comment by igosheva** [comment]
.section__title - тоже самое нужно сделать со всеми заголовками -  добавить font-weight: 500;

**Comment by EgorKorol** [comment]
Ааа fixed
