### ISSUE TITLE
Ошибки в консоле

### ISSUE THREAD

**Issue by igosheva** [EgorKorol/burgers#6]
5 ошибок в консоле - не может найти картинки

**Comment by EgorKorol** [comment]
В scss пишем пути так же как было бы в css?

**Comment by igosheva** [comment]
Нет, по сути да. Толкьо сейчас у тебя пути url(../../img/bg/footer.jpg), а надо url(../img/bg/footer.jpg)

**Comment by EgorKorol** [comment]
Ага ,понял
